name: RM Job Notifier

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Create environment file
        run: |
          echo "RM_USERNAME=${{ secrets.RM_USERNAME }}" >> .env
          echo "RM_PASSWORD=${{ secrets.RM_PASSWORD }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

      - name: Run notifier
        run: npm start